sudo: required
dist: trusty

language: c
compiler:
    - gcc

before_install:
    - sudo apt-get -y install check

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make && make test
